{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki.mariadb.fullname" . }}
  labels:
    {{- include "mediawiki.mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mariadb.service.type }}
  ports:
    - port: {{ .Values.mariadb.service.port }}
      targetPort: 3306
      protocol: TCP
  selector:
    {{- include "mediawiki.mariadb.selectorLabels" . | nindent 4 }}
{{- end }}
