apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mediawiki.fullname" . }}-secret
  labels:
    {{- include "mediawiki.labels" . | nindent 4 }}
type: Opaque
data:
  MW_SITENAME: {{ .Values.mediawiki.sitename | b64enc | quote }}
  MW_SERVER: {{ .Values.mediawiki.server | b64enc | quote }}
  MW_DB_SERVER: {{ (.Values.mediawiki.db.server | default (include "mediawiki.mariadb.fullname" .)) | b64enc | quote }}
  MW_DB_NAME: {{ .Values.mediawiki.db.name | b64enc | quote }}
  MW_DB_USER: {{ .Values.mediawiki.db.user | b64enc | quote }}
  MW_DB_PASSWORD: {{ .Values.mediawiki.db.password | b64enc | quote }}
  MW_SECRET_KEY: {{ .Values.mediawiki.secretKey | b64enc | quote }}
  MW_UPGRADE_KEY: {{ .Values.mediawiki.upgradeKey | b64enc | quote }}
  {{- if .Values.mediawiki.oidc.enabled }}
  MW_OIDC_PROVIDER_URL: {{ .Values.mediawiki.oidc.providerURL | b64enc | quote }}
  MW_OIDC_CLIENT_ID: {{ .Values.mediawiki.oidc.clientID | b64enc | quote }}
  MW_OIDC_CLIENT_SECRET: {{ .Values.mediawiki.oidc.clientSecret | b64enc | quote }}
  {{- end }}
