apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mediawiki
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/dragonhunter274/Mediawiki
  ref:
    branch: master
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/dragonhunter274/Mediawiki/master/flux/helmrelease.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mediawiki
  namespace: mediawiki
spec:
  interval: 10m
  chart:
    spec:
      chart: ./mediawiki-chart
      sourceRef:
        kind: GitRepository
        name: mediawiki
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: mediawiki-credentials
      valuesKey: server
      targetPath: mediawiki.server
    - kind: Secret
      name: mediawiki-credentials
      valuesKey: password
      targetPath: mediawiki.db.password
    - kind: Secret
      name: mediawiki-credentials
      valuesKey: rootPassword
      targetPath: mediawiki.db.rootPassword
    - kind: Secret
      name: mediawiki-credentials
      valuesKey: secretKey
      targetPath: mediawiki.secretKey
    - kind: Secret
      name: mediawiki-credentials
      valuesKey: upgradeKey
      targetPath: mediawiki.upgradeKey
    - kind: Secret
      name: mediawiki-credentials
      valuesKey: oidcProviderURL
      targetPath: mediawiki.oidc.providerURL
      optional: true
    - kind: Secret
      name: mediawiki-credentials
      valuesKey: oidcClientID
      targetPath: mediawiki.oidc.clientID
      optional: true
    - kind: Secret
      name: mediawiki-credentials
      valuesKey: oidcClientSecret
      targetPath: mediawiki.oidc.clientSecret
      optional: true
  values:
    replicaCount: 2
    image:
      repository: dragonhunter274/mediawiki
      pullPolicy: IfNotPresent
      tag: "latest"
    service:
      type: LoadBalancer
      port: 8080
      targetport: 8080
    mariadb:
      enabled: true
      image:
        repository: mariadb
        tag: "latest"
      service:
        type: ClusterIP
        port: 3306
      storage: 5Gi
    mediawiki:
      sitename: "MyWiki"
      scriptPath: ""
      languageCode: "en"
      localtimezone: "UTC"
      defaultSkin: "citizen"
      enableEmail: false
      enableUserEmail: true
      enableUploads: false
      useInstantCommons: false
      pingback: false
      oidc:
        enabled: false
        autoLogin: false
        enableLocalLogin: true
        scope: "openid profile email"
        buttonLabel: "Login with OIDC"
        preferredUsername: "preferred_username"
        migrateUsersByEmail: false
        useEmailAsUsername: false
        groupSync:
          enabled: false
          claim: "groups"
          map: {}
          # Example:
          #   map:
          #     sysop: "wiki-admins"
          #     bureaucrat: "wiki-admins"
      extraSettings: ""
